import { persistentAtom } from '@nanostores/persistent';
import { computed } from 'nanostores';
import type { Task, Subtask, TaskStatus } from '../types';
import { seedTasks } from '../lib/seed';
import { generateId, createSubtask, todayISO, formatDate } from '../lib/utils';
import { addToast } from './ui';

// Helper to parse JSON with fallback
function parseTasks(value: string): Task[] {
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function stringifyTasks(tasks: Task[]): string {
  return JSON.stringify(tasks);
}

export const tasks = persistentAtom<Task[]>('kmm-tasks', seedTasks, {
  encode: stringifyTasks,
  decode: parseTasks,
});

/** Get all tasks sorted by order */
export const sortedTasks = computed(tasks, ($tasks) =>
  [...$tasks].sort((a, b) => a.order - b.order)
);

/** Get tasks for a specific list */
export function getTasksByList(listId: string): Task[] {
  return tasks
    .get()
    .filter((t) => t.listId === listId)
    .sort((a, b) => a.order - b.order);
}

/** Get a task by ID */
export function getTaskById(id: string): Task | undefined {
  return tasks.get().find((t) => t.id === id);
}

/** Create a new task */
export function createTask(task: Omit<Task, 'id' | 'createdAt'>): Task {
  const current = tasks.get();
  const newTask: Task = {
    ...task,
    id: generateId(),
    createdAt: new Date().toISOString(),
  };
  tasks.set([...current, newTask]);
  return newTask;
}

/** Update a task */
export function updateTask(id: string, patch: Partial<Task>): void {
  tasks.set(
    tasks.get().map((t) => (t.id === id ? { ...t, ...patch } : t))
  );
}

/** Delete a task */
export function deleteTask(id: string): void {
  tasks.set(tasks.get().filter((t) => t.id !== id));
}

/** Calculate the next due date based on the recurring interval */
function getNextRecurringDate(dueDate: string | null, interval: 'daily' | 'weekly' | 'monthly'): string {
  const base = dueDate ? new Date(dueDate) : new Date();
  base.setHours(0, 0, 0, 0);

  if (interval === 'daily') {
    base.setDate(base.getDate() + 1);
  } else if (interval === 'weekly') {
    base.setDate(base.getDate() + 7);
  } else if (interval === 'monthly') {
    base.setMonth(base.getMonth() + 1);
  }

  return base.toISOString();
}

/**
 * Complete a single recurring occurrence (used by Calendar/Combined views).
 * Adds the given date key (YYYY-MM-DD) to the task's completedDates.
 * The occurrence is marked done on that day; future occurrences remain todo.
 */
export function completeRecurringOccurrence(taskId: string, dateKey: string): void {
  const task = getTaskById(taskId);
  if (!task) return;

  const completed = task.completedDates ?? [];
  if (completed.includes(dateKey)) return;

  updateTask(taskId, { completedDates: [...completed, dateKey] });
}

/**
 * Un-complete a single recurring occurrence (from Calendar/Combined views).
 * Removes the given date key from the task's completedDates.
 */
export function uncompleteRecurringOccurrence(taskId: string, dateKey: string): void {
  const task = getTaskById(taskId);
  if (!task) return;

  const completed = task.completedDates ?? [];
  updateTask(taskId, { completedDates: completed.filter((d) => d !== dateKey) });
}

/**
 * Toggle a single recurring occurrence's done state (Calendar/Combined views).
 */
export function toggleRecurringOccurrence(taskId: string, dateKey: string): void {
  const task = getTaskById(taskId);
  if (!task) return;

  const completed = task.completedDates ?? [];
  if (completed.includes(dateKey)) {
    uncompleteRecurringOccurrence(taskId, dateKey);
  } else {
    completeRecurringOccurrence(taskId, dateKey);
  }
}

/**
 * Deactivate a recurring task entirely: it becomes a plain done task
 * (no more future occurrences generated by the calendar).
 */
function deactivateRecurringTask(id: string, title: string): void {
  updateTask(id, {
    status: 'done',
    isRecurring: false,
    recurringInterval: null,
  });
  addToast(`"${title}" completed`, 'success');
}

/**
 * Toggle task status (Board/List views — the task as a whole).
 * If the task is recurring and being marked done, it is deactivated
 * (isRecurring=false) so it disappears from future occurrences and
 * appears only in the Done/Completed section.
 */
export function toggleTaskStatus(id: string): void {
  const task = getTaskById(id);
  if (!task) return;

  const newStatus: TaskStatus = task.status === 'done' ? 'todo' : 'done';

  if (newStatus === 'done' && task.isRecurring) {
    deactivateRecurringTask(task.id, task.title);
  } else {
    updateTask(id, { status: newStatus });
  }
}

/** Set task status (Board/Agenda — the task as a whole) */
export function setTaskStatus(id: string, status: TaskStatus): void {
  const task = getTaskById(id);
  if (!task) return;

  if (status === 'done' && task.status !== 'done' && task.isRecurring) {
    deactivateRecurringTask(task.id, task.title);
  } else {
    updateTask(id, { status });
  }
}

/** Reorder tasks within a list */
export function reorderTasks(listId: string, orderedIds: string[]): void {
  const current = tasks.get();
  const orderMap = new Map(orderedIds.map((id, index) => [id, index]));

  tasks.set(
    current.map((t) => {
      if (t.listId !== listId) return t;
      const order = orderMap.get(t.id);
      return order !== undefined ? { ...t, order } : t;
    })
  );
}

/** Reorder tasks within a board column (by status) */
export function reorderTasksByStatus(status: TaskStatus, orderedIds: string[]): void {
  const current = tasks.get();
  const orderMap = new Map(orderedIds.map((id, index) => [id, index]));

  tasks.set(
    current.map((t) => {
      if (t.status !== status) return t;
      const order = orderMap.get(t.id);
      return order !== undefined ? { ...t, order } : t;
    })
  );
}

/** Move a task to a new status and place it at the end of that column */
export function moveTaskToStatus(id: string, newStatus: TaskStatus): void {
  const task = getTaskById(id);
  if (!task || task.status === newStatus) return;

  // Find the max order in the target status column
  const maxOrder = tasks
    .get()
    .filter((t) => t.status === newStatus)
    .reduce((max, t) => Math.max(max, t.order), -1);

  // If moving a recurring task to "done" (e.g. via drag&drop in the Board),
  // deactivate the recurrence so it stops generating future occurrences.
  if (newStatus === 'done' && task.isRecurring) {
    deactivateRecurringTask(task.id, task.title);
    updateTask(id, { order: maxOrder + 1 });
    return;
  }

  updateTask(id, { status: newStatus, order: maxOrder + 1 });
}

/** Add a subtask to a task */
export function addSubtask(taskId: string, title: string): void {
  const task = getTaskById(taskId);
  if (!task) return;

  const newSubtask = createSubtask(title, task.subtasks.length);
  updateTask(taskId, {
    subtasks: [...task.subtasks, newSubtask],
  });
}

/** Toggle a subtask's done state */
export function toggleSubtask(taskId: string, subtaskId: string): void {
  const task = getTaskById(taskId);
  if (!task) return;

  updateTask(taskId, {
    subtasks: task.subtasks.map((s) =>
      s.id === subtaskId ? { ...s, done: !s.done } : s
    ),
  });
}

/** Delete a subtask */
export function deleteSubtask(taskId: string, subtaskId: string): void {
  const task = getTaskById(taskId);
  if (!task) return;

  updateTask(taskId, {
    subtasks: task.subtasks.filter((s) => s.id !== subtaskId),
  });
}

/** Reorder subtasks within a task */
export function reorderSubtasks(taskId: string, orderedIds: string[]): void {
  const task = getTaskById(taskId);
  if (!task) return;

  const orderMap = new Map(orderedIds.map((id, index) => [id, index]));
  updateTask(taskId, {
    subtasks: task.subtasks
      .map((s) => {
        const order = orderMap.get(s.id);
        return order !== undefined ? { ...s, order } : s;
      })
      .sort((a, b) => a.order - b.order),
  });
}

/**
 * Boomerang check: reschedule overdue tasks with boomerangDays set
 * Run on app mount. Returns number of tasks rescheduled.
 */
export function runBoomerangCheck(): number {
  const current = tasks.get();
  const today = todayISO();
  let rescheduled = 0;
  const rescheduledTitles: string[] = [];

  const updated = current.map((task) => {
    if (
      task.status === 'todo' &&
      task.dueDate &&
      task.boomerangDays !== null &&
      task.boomerangDays > 0
    ) {
      const due = new Date(task.dueDate);
      due.setHours(0, 0, 0, 0);
      const todayDate = new Date(today);
      todayDate.setHours(0, 0, 0, 0);

      const diffDays = Math.round(
        (todayDate.getTime() - due.getTime()) / (1000 * 60 * 60 * 24)
      );

      if (diffDays >= task.boomerangDays) {
        rescheduled++;
        rescheduledTitles.push(task.title);
        return { ...task, dueDate: today };
      }
    }
    return task;
  });

  if (rescheduled > 0) {
    tasks.set(updated);
  }

  // Emit a per-task toast for each boomerang reschedule
  for (const title of rescheduledTitles) {
    addToast(`🪃 ${title} moved to today!`, 'info');
  }

  return rescheduled;
}

/** Delete all tasks with status "done" (destructive, used from Settings) */
export function clearCompletedTasks(): number {
  const current = tasks.get();
  const completed = current.filter((t) => t.status === 'done');
  if (completed.length === 0) return 0;

  tasks.set(current.filter((t) => t.status !== 'done'));
  return completed.length;
}

/** Get count of tasks in a list */
export function getTaskCountByList(listId: string): number {
  return tasks.get().filter((t) => t.listId === listId).length;
}

/** Get count of incomplete tasks in a list */
export function getIncompleteTaskCountByList(listId: string): number {
  return tasks
    .get()
    .filter((t) => t.listId === listId && t.status !== 'done').length;
}