<script lang="ts">
  import {
    User,
    Briefcase,
    ShoppingBag,
    ListTodo,
    Calendar,
    LayoutGrid,
    CheckSquare,
    StickyNote,
    Plus,
    Sun,
    Moon,
    Home,
    Sparkles,
    Layers,
    FileText,
    Trash2,
    Check,
    Clock,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    X,
    GripVertical,
    RotateCcw,
    AlertCircle,
    Bookmark,
    Folder,
    Heart,
    Star,
    PenLine,
    BookOpen,
    Dumbbell,
    Plane,
    Coffee,
    Music,
    Camera,
    Wallet,
    Gift,
    MoreHorizontal,
    SlidersHorizontal,
    Filter,
    Search,
  } from 'lucide-svelte';

  let {
    name = 'list-todo',
    size = 18,
    class: className = '',
  }: { name?: string; size?: number; class?: string } = $props();

  const iconMap: Record<string, any> = {
    user: User,
    briefcase: Briefcase,
    'shopping-bag': ShoppingBag,
    'list-todo': ListTodo,
    calendar: Calendar,
    'layout-grid': LayoutGrid,
    'check-square': CheckSquare,
    'sticky-note': StickyNote,
    plus: Plus,
    sun: Sun,
    moon: Moon,
    home: Home,
    sparkles: Sparkles,
    layers: Layers,
    'file-text': FileText,
    'trash-2': Trash2,
    check: Check,
    clock: Clock,
    'chevron-down': ChevronDown,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    x: X,
    'grip-vertical': GripVertical,
    'rotate-ccw': RotateCcw,
    'alert-circle': AlertCircle,
    bookmark: Bookmark,
    folder: Folder,
    heart: Heart,
    star: Star,
    'pen-line': PenLine,
    'book-open': BookOpen,
    dumbbell: Dumbbell,
    plane: Plane,
    coffee: Coffee,
    music: Music,
    camera: Camera,
    wallet: Wallet,
    gift: Gift,
    'more-horizontal': MoreHorizontal,
    'sliders-horizontal': SlidersHorizontal,
    filter: Filter,
    search: Search,
  };
</script>

{#if iconMap[name]}
  {@const IconComponent = iconMap[name]}
  <IconComponent {size} class={className} />
{:else}
  <ListTodo {size} class={className} />
{/if}